package addressbook.tests;// Generated by Selenium IDE

import addressbook.model.GroupData;
import org.junit.Assert;
import org.junit.Test;
import org.junit.jupiter.api.Assertions;

public class GroupDeleteTest extends TestBase {


  @Test
  public void groupDelete() {
    app.getNavigationHelper().goToGroupPage();
    int before = app.getGroupHelper().getGroupCount();
    if(! app.getGroupHelper().isThereAGroup()){
      app.getGroupHelper().createGroup(new GroupData("test1", null, null));
    }
    app.getGroupHelper().selectGroup();
    app.getGroupHelper().deleteSelectedGroups();
    app.getGroupHelper().returnToGroupPage();
    int after = app.getGroupHelper().getGroupCount();
    Assertions.assertEquals(after, before - 1);

  }

}
