package addressbook.tests;// Generated by Selenium IDE

import org.junit.Test;

public class GroupDeleteTest extends TestBase {


  @Test
  public void groupDelete() {
    app.getNavigationHelper().goToGroupPage();
    app.getGroupHelper().selectGroup();
    app.getGroupHelper().deleteSelectedGroups();
    app.getGroupHelper().returnToGroupPage();
  }

}
