package addressbook.tests;// Generated by Selenium IDE

import addressbook.model.GroupData;
import org.junit.Test;

public class GroupDeleteTest extends TestBase {


  @Test
  public void groupDelete() {
    app.getNavigationHelper().goToGroupPage();
    if(! app.getGroupHelper().isThereAGroup()){
      app.getGroupHelper().createGroup(new GroupData("test1", null, null));
    }
    app.getGroupHelper().selectGroup();
    app.getGroupHelper().deleteSelectedGroups();
    app.getGroupHelper().returnToGroupPage();
  }

}
